name: Tag packages
description: Creates tags for packages based on changes to CHANGELOG.md files.

inputs:
  token:
    description: "Access Token (usually PAT) used to push tags in a way that triggers actions."
    required: true
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        token: ${{ inputs.token }}

    - name: Tag packages
      run: ${{ github.action_path }}/tag-packages.sh
      shell: bash
