name: Publish a package on pub.dev
description: Publish a new package on pub.dev and create a tag.

runs:
  using: composite

  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@main

    - name: Setup Flutter
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: latest

    - name: Setup pub.dev credentials
      uses: flutter-actions/setup-pubdev-credentials@v1

    - run: ${{ github.action_path }}/publish-package.sh
      shell: bash
