name: Publish a package on pub.dev
description: Publish a new package on pub.dev and create a tag.

runs:
  using: composite

  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2

    - run: ${{ github.action_path }}/publish-package.sh
      shell: bash
