name: Publish a package
description: Publishes a package from a tag to pub.dev with support for monorepos.

inputs:
  path:
    description: 'Template path for packages to publish (e.g. "packages/{NAME}").'
    required: true
    default: "{NAME}"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Dart
      uses: dart-lang/setup-dart@main

    - name: Setup Flutter
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable
        version: latest

    - name: Setup pub.dev credentials
      uses: flutter-actions/setup-pubdev-credentials@v1

    - name: Publish to pub.dev
      shell: bash
      env:
        PACKAGE_PATH: ${{ inputs.path }}
      run: |
        TAG=$(git describe --exact-match --tags)
        PACKAGE_NAME=$(echo $TAG | cut -d "-" -f 1)
        PACKAGE_PATH=$(echo $PACKAGE_PATH | sed "s/{NAME}/$PACKAGE_NAME/g")

        echo "PACKAGE_NAME=$PACKAGE_NAME"
        echo "PACKAGE_PATH=$PACKAGE_PATH"

        if [ -f "$PACKAGE_PATH/pubspec.yaml" ]; then
          cd $PACKAGE_PATH
          flutter pub publish --force
        else 
          echo "No package found at $PACKAGE_PATH"
          exit 1
        fi
